name: Setup
description: Sets up Node.js and Yarn

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.0

    - name: Install dependencies
      shell: bash

      run: bun install --frozen-lockfile
