export interface PrismTheme {
  colors: {
    background: string;
    foreground: string;
    [key: string]: string;
  };
}

export const themes = {
  blueVelvetTheme: {
    colors: {
      'background': '#282c34',
      'foreground': '#abb2bf',
      'keyword': '#7c8495',
      'boolean': '#10b1fe',
      'function': '#7a82da',
      'string': '#636d83',
      'number': '#ff78f8',
      'operator': '#7a82da',
      'punctuation': '#636d83',
      'comment': '#abb2bf',
      'class-name': '#ff6480',
      'maybe-class-name': '#ff6480',
      'constant': '#7a82da',
      'symbol': '#9f7efe',
      'property': '#abb2bf',
      'parameter': '#abb2bf',
      'variable': '#10b1fe',
      'tag': '#3691ff',
      'attr-name': '#ff936a',
      'attr-value': '#f9c859',
      'selector': '#3691ff',
      'method': '#3fc56b',
      'console': '#ff6480',
    },
  },
  defaultColorTheme: {
    colors: {
      'background': '#171c2a',
      'foreground': '#FFFFFFcc',
      'keyword': '#ffd866',
      'boolean': '#fc6a67',
      'function': '#FFFFFFcc',
      'string': '#868d9caa',
      'number': '#fc6a67',
      'operator': '#ffd866',
      'punctuation': '#868d9caa',
      'comment': '#868d9caa',
      'class-name': '#7E9E2D',
      'maybe-class-name': '#7E9E2D',
      'constant': '#fc6a67',
      'symbol': '#fc6a67',
      'property': '#FFFFFFcc',
      'parameter': '#fc9867',
      'variable': '#fc9867',
      'tag': '#ffd866',
      'attr-name': '#fc9867',
      'attr-value': '#868d9caa',
      'selector': '#78dce8',
      'method': '#e991e3',
      'console': '#FFFFFFcc',
    },
  },
  draculaTheme: {
    colors: {
      'background': '#171c2a',
      'foreground': '#FFFFFFcc',
      'keyword': '#BD93F9',
      'boolean': '#BD93F9',
      'function': '#50FA7B',
      'string': '#FF79C6',
      'number': '#BD93F9',
      'operator': '#50FA7B',
      'punctuation': '#8BE9FD',
      'comment': '#6272A4',
      'class-name': '#8BE9FD',
      'maybe-class-name': '#8BE9FD',
      'constant': '#BD93F9',
      'symbol': '#BD93F9',
      'property': '#8BE9FD',
      'parameter': '#BD93F9',
      'variable': '#BD93F9',
      'tag': '#FF79C6',
      'attr-name': '#FF79C6',
      'attr-value': '#F1FA8C',
      'selector': '#FF79C6',
      'method': '#50FA7B',
      'console': '#8BE9FD',
    },
  },
  officialTheme: {
    colors: {
      'background': '#101e2c',
      'foreground': '#bdd2e7',
      'keyword': '#00b1ff',
      'boolean': '#ffdc96',
      'function': '#9696ff',
      'string': '#dbd4ba',
      'number': '#ffb482',
      'operator': '#ff7878',
      'punctuation': '#bdd2e7',
      'comment': '#647882',
      'class-name': '#9696ff',
      'maybe-class-name': '#9696ff',
      'constant': '#aae682',
      'symbol': '#ffdc96',
      'property': '#9696ff',
      'parameter': '#00dcdc',
      'variable': '#00b1ff',
      'tag': '#dc8cff',
      'attr-name': '#9696ff',
      'attr-value': '#aae682',
      'selector': '#dc8cff',
      'method': '#00b1ff',
    },
  },
  peaceOfEyeDraculaTheme: {
    colors: {
      'background': '#122033',
      'foreground': '#FFFFFFcc',
      'keyword': '#BD93F9',
      'boolean': '#BD93F9',
      'function': '#50FA7B',
      'string': '#FF79C6',
      'number': '#BD93F9',
      'operator': '#50FA7B',
      'punctuation': '#8BE9FD',
      'comment': '#6272A4',
      'class-name': '#8BE9FD',
      'maybe-class-name': '#8BE9FD',
      'constant': '#BD93F9',
      'symbol': '#BD93F9',
      'property': '#8BE9FD',
      'parameter': '#BD93F9',
      'variable': '#BD93F9',
      'tag': '#FF79C6',
      'attr-name': '#FF79C6',
      'attr-value': '#F1FA8C',
      'selector': '#FF79C6',
      'method': '#50FA7B',
      'console': '#8BE9FD',
    },
  },
  peaceOfEyeTheme: {
    colors: {
      'background': '#122033',
      'foreground': '#FFFFFFcc',
      'keyword': '#ffd866',
      'boolean': '#fc6a67',
      'function': '#FFFFFFcc',
      'string': '#868d9caa',
      'number': '#fc6a67',
      'operator': '#ffd866',
      'punctuation': '#868d9caa',
      'comment': '#868d9caa',
      'class-name': '#7E9E2D',
      'maybe-class-name': '#7E9E2D',
      'constant': '#fc6a67',
      'symbol': '#fc6a67',
      'property': '#FFFFFFcc',
      'parameter': '#fc9867',
      'variable': '#fc9867',
      'tag': '#ffd866',
      'attr-name': '#fc9867',
      'attr-value': '#868d9caa',
      'selector': '#78dce8',
      'method': '#e991e3',
      'console': '#FFFFFFcc',
    },
  },
  professionalTheme: {
    colors: {
      'background': '#1c1e2e',
      'foreground': '#c8d3f5',
      'keyword': '#c099ff',
      'boolean': '#7f85a3',
      'function': '#82aaff',
      'string': '#7a88cf',
      'number': '#ff966c',
      'operator': '#c099ff',
      'punctuation': '#7a88cf',
      'comment': '#7a88cf',
      'class-name': '#ffc777',
      'maybe-class-name': '#ffc777',
      'constant': '#c8d3f5',
      'symbol': '#c3e88d',
      'property': '#c8d3f5',
      'parameter': '#c8d3f5',
      'variable': '#c8d3f5',
      'tag': '#ff757f',
      'attr-name': '#c099ff',
      'attr-value': '#7a88cf',
      'selector': '#ff757f',
      'method': '#82aaff',
      'console': '#ffc777',
    },
  },
  shadesOfGreyTheme: {
    colors: {
      'background': '#24292e',
      'foreground': '#e1e4e8',
      'keyword': '#c74ded',
      'boolean': '#00e8c6',
      'function': '#FFE66D',
      'string': '#7cb7ff',
      'number': '#f39c12',
      'operator': '#c74ded',
      'punctuation': '#D5CED9',
      'comment': '#5f6167',
      'class-name': '#FFE66D',
      'maybe-class-name': '#FFE66D',
      'constant': '#D5CED9',
      'symbol': '#00e8c6',
      'property': '#00e8c6',
      'parameter': '#00e8c6',
      'variable': '#00e8c6',
      'tag': '#00e8c6',
      'attr-name': '#f39c12',
      'attr-value': '#96E072',
      'selector': '#00e8c6',
      'method': '#FFE66D',
      'console': '#00e8c6',
    },
  },
  simpleAsLightTheme: {
    colors: {
      'background': '#ffffff',
      'foreground': '#455059',
      'keyword': '#c9a022',
      'boolean': '#C13838',
      'function': '#455059',
      'string': '#8b99a7aa',
      'number': '#C13838',
      'operator': '#c9a022',
      'punctuation': '#8b99a7aa',
      'comment': '#8b99a7aa',
      'class-name': '#7E9E2D',
      'maybe-class-name': '#7E9E2D',
      'constant': '#C13838',
      'symbol': '#C13838',
      'property': '#455059',
      'parameter': '#D26D32',
      'variable': '#D26D32',
      'tag': '#c9a022',
      'attr-name': '#D26D32',
      'attr-value': '#8b99a7aa',
      'selector': '#3398DB',
      'method': '#CC71BC',
      'console': '#455059',
    },
  },
  traditionalTheme: {
    colors: {
      'background': '#242424',
      'foreground': '#cccccc',
      'keyword': '#CCCCCC',
      'boolean': '#CC8242',
      'function': '#FFC66D',
      'string': '#6A8759',
      'number': '#7A9EC2',
      'operator': '#CCCCCC',
      'punctuation': '#CC8242',
      'comment': '#707070',
      'class-name': '#7A9EC2',
      'maybe-class-name': '#7A9EC2',
      'constant': '#7A9EC2',
      'property': '#9E7BB0',
      'parameter': '#CCCCCC',
      'variable': '#CCCCCC',
      'attr-name': '#CCCCCC',
      'selector': '#FFC66D',
    },
  },
  vintageTheme: {
    colors: {
      'background': '#23272e',
      'foreground': '#abb2bf',
      'keyword': '#d19a66',
      'boolean': '#d19a66',
      'function': '#77C2CE',
      'string': '#98c379',
      'number': '#d19a66',
      'operator': '#d19a66',
      'punctuation': '#e06c75',
      'comment': '#5c6370',
      'class-name': '#e5c07b',
      'maybe-class-name': '#e5c07b',
      'constant': '#e06c75',
      'symbol': '#56b6c2',
      'property': '#e06c75',
      'parameter': '#e5c07b',
      'variable': '#c678dd',
      'tag': '#e06c75',
      'attr-name': '#d19a66',
      'attr-value': '#98c379',
      'selector': '#e06c75',
      'method': '#77C2CE',
    },
  },
} as const;

export type ThemeName = keyof typeof themes;
