import type { Token } from './NativeLibprisma';
import NativeLibprisma from './NativeLibprisma';

export type { Token };

/**
 * Supported programming languages for syntax highlighting.
 * Comprehensive list of all languages and their aliases supported by LibPrisma.
 * Based on Prism.js language support.
 */
export type Language =
  // Markup & Web
  | 'markup'
  | 'html'
  | 'xml'
  | 'svg'
  | 'mathml'
  | 'ssml'
  | 'atom'
  | 'rss'
  | 'css'
  | 'scss'
  | 'sass'
  | 'less'
  | 'stylus'
  | 'javascript'
  | 'js'
  | 'typescript'
  | 'ts'
  | 'jsx'
  | 'tsx'
  | 'json'
  | 'json5'
  | 'jsonp'
  | 'webmanifest'
  | 'markdown'
  | 'md'
  | 'yaml'
  | 'yml'

  // System & Shell
  | 'bash'
  | 'sh'
  | 'shell'
  | 'shell-session'
  | 'sh-session'
  | 'shellsession'
  | 'powershell'
  | 'batch'
  | 'makefile'
  | 'dockerfile'
  | 'docker'
  | 'nginx'
  | 'apache'
  | 'apacheconf'
  | 'git'
  | 'ignore'
  | 'gitignore'
  | 'hgignore'
  | 'npmignore'
  | 'ini'
  | 'toml'
  | 'properties'
  | 'editorconfig'

  // Programming Languages
  | 'c'
  | 'cpp'
  | 'clike'
  | 'csharp'
  | 'cs'
  | 'dotnet'
  | 'java'
  | 'python'
  | 'py'
  | 'ruby'
  | 'rb'
  | 'go'
  | 'rust'
  | 'swift'
  | 'kotlin'
  | 'kt'
  | 'kts'
  | 'scala'
  | 'php'
  | 'perl'
  | 'lua'
  | 'r'
  | 'dart'
  | 'julia'
  | 'haskell'
  | 'hs'
  | 'elixir'
  | 'erlang'
  | 'clojure'
  | 'lisp'
  | 'emacs'
  | 'elisp'
  | 'emacs-lisp'
  | 'scheme'
  | 'racket'
  | 'rkt'
  | 'ocaml'
  | 'fsharp'
  | 'elm'
  | 'purescript'
  | 'd'
  | 'nim'
  | 'crystal'
  | 'zig'
  | 'reason'
  | 'rescript'
  | 'res'
  | 'v'
  | 'odin'

  // JVM Languages
  | 'groovy'
  | 'gradle'

  // .NET Languages
  | 'vbnet'
  | 'visual-basic'
  | 'vb'
  | 'vba'
  | 'fsharp'

  // Mobile & Apple
  | 'objectivec'
  | 'objc'
  | 'swift'

  // Web Frameworks & Templates
  | 'django'
  | 'jinja2'
  | 'ejs'
  | 'eta'
  | 'erb'
  | 'handlebars'
  | 'hbs'
  | 'mustache'
  | 'twig'
  | 'pug'
  | 'haml'
  | 'liquid'
  | 'smarty'
  | 'velocity'
  | 'ftl'
  | 'jsp'
  | 'aspnet'

  // Database & Query
  | 'sql'
  | 'plsql'
  | 'tsql'
  | 'mongodb'
  | 'graphql'
  | 'cypher'
  | 'sparql'
  | 'n1ql'

  // Data & Config
  | 'xml'
  | 'yaml'
  | 'yml'
  | 'toml'
  | 'csv'
  | 'ini'

  // Assembly
  | 'asm6502'
  | 'armasm'
  | 'arm-asm'
  | 'nasm'
  | 'mips'
  | 'asmatmel'

  // Functional
  | 'haskell'
  | 'hs'
  | 'elm'
  | 'ocaml'
  | 'erlang'
  | 'elixir'
  | 'clojure'
  | 'fsharp'

  // Systems
  | 'c'
  | 'cpp'
  | 'rust'
  | 'go'
  | 'd'
  | 'nim'
  | 'zig'
  | 'ada'

  // Scripting
  | 'python'
  | 'py'
  | 'ruby'
  | 'rb'
  | 'perl'
  | 'lua'
  | 'tcl'
  | 'r'

  // Misc Languages
  | 'abap'
  | 'abnf'
  | 'actionscript'
  | 'agda'
  | 'al'
  | 'antlr4'
  | 'g4'
  | 'apex'
  | 'apl'
  | 'applescript'
  | 'aql'
  | 'arduino'
  | 'ino'
  | 'arff'
  | 'arturo'
  | 'art'
  | 'asciidoc'
  | 'adoc'
  | 'autohotkey'
  | 'autoit'
  | 'avisynth'
  | 'avs'
  | 'avro-idl'
  | 'avdl'
  | 'awk'
  | 'gawk'
  | 'basic'
  | 'bbcode'
  | 'shortcode'
  | 'bbj'
  | 'bicep'
  | 'birb'
  | 'bison'
  | 'bnf'
  | 'rbnf'
  | 'bqn'
  | 'brainfuck'
  | 'brightscript'
  | 'bro'
  | 'cfscript'
  | 'cfc'
  | 'chaiscript'
  | 'cil'
  | 'cilkc'
  | 'cilk-c'
  | 'cilkcpp'
  | 'cilk-cpp'
  | 'cilk'
  | 'cmake'
  | 'cobol'
  | 'coffeescript'
  | 'coffee'
  | 'concurnas'
  | 'conc'
  | 'cooklang'
  | 'csp'
  | 'cue'
  | 'dataweave'
  | 'dax'
  | 'dhall'
  | 'diff'
  | 'dns-zone-file'
  | 'dns-zone'
  | 'dot'
  | 'gv'
  | 'ebnf'
  | 'eiffel'
  | 'etlua'
  | 'excel-formula'
  | 'xlsx'
  | 'xls'
  | 'factor'
  | 'false'
  | 'fift'
  | 'firestore-security-rules'
  | 'flow'
  | 'fortran'
  | 'func'
  | 'gcode'
  | 'gdscript'
  | 'gedcom'
  | 'gettext'
  | 'po'
  | 'gml'
  | 'gamemakerlanguage'
  | 'glsl'
  | 'gn'
  | 'gni'
  | 'linker-script'
  | 'ld'
  | 'go-module'
  | 'go-mod'
  | 'gap'
  | 'haxe'
  | 'hcl'
  | 'hlsl'
  | 'hoon'
  | 'hpkp'
  | 'hsts'
  | 'http'
  | 'uri'
  | 'url'
  | 'ichigojam'
  | 'icon'
  | 'icu-message-format'
  | 'idris'
  | 'idr'
  | 'inform7'
  | 'io'
  | 'j'
  | 'javadoc'
  | 'javadoclike'
  | 'javastacktrace'
  | 'jq'
  | 'jsdoc'
  | 'jsstacktrace'
  | 'jolie'
  | 'keepalived'
  | 'keyman'
  | 'kusto'
  | 'latex'
  | 'tex'
  | 'context'
  | 'latte'
  | 'lilypond'
  | 'ly'
  | 'livescript'
  | 'llvm'
  | 'log'
  | 'lolcode'
  | 'magma'
  | 'mata'
  | 'matlab'
  | 'maxscript'
  | 'mel'
  | 'mermaid'
  | 'metafont'
  | 'mizar'
  | 'monkey'
  | 'moonscript'
  | 'moon'
  | 'n1ql'
  | 'n4js'
  | 'n4jsd'
  | 'nand2tetris-hdl'
  | 'naniscript'
  | 'nani'
  | 'neon'
  | 'nevod'
  | 'nix'
  | 'nsis'
  | 'opencl'
  | 'openqasm'
  | 'qasm'
  | 'oz'
  | 'parigp'
  | 'parser'
  | 'pascal'
  | 'objectpascal'
  | 'pascaligo'
  | 'pcaxis'
  | 'px'
  | 'peoplecode'
  | 'pcode'
  | 'phpdoc'
  | 'plant-uml'
  | 'plantuml'
  | 'powerquery'
  | 'pq'
  | 'mscript'
  | 'processing'
  | 'prolog'
  | 'promql'
  | 'protobuf'
  | 'psl'
  | 'puppet'
  | 'purebasic'
  | 'pbfasm'
  | 'q'
  | 'qml'
  | 'qore'
  | 'qsharp'
  | 'qs'
  | 'cshtml'
  | 'razor'
  | 'regex'
  | 'rego'
  | 'renpy'
  | 'rpy'
  | 'rest'
  | 'rip'
  | 'roboconf'
  | 'robotframework'
  | 'robot'
  | 'sas'
  | 'smali'
  | 'smalltalk'
  | 'sml'
  | 'smlnj'
  | 'solidity'
  | 'sol'
  | 'solution-file'
  | 'sln'
  | 'soy'
  | 'splunk-spl'
  | 'sqf'
  | 'squirrel'
  | 'stan'
  | 'stata'
  | 'iecst'
  | 'supercollider'
  | 'sclang'
  | 'systemd'
  | 'tact'
  | 't4-templating'
  | 't4-cs'
  | 't4'
  | 't4-vb'
  | 'tap'
  | 'textile'
  | 'tt2'
  | 'tremor'
  | 'trickle'
  | 'troy'
  | 'tl'
  | 'tlb'
  | 'typoscript'
  | 'tsconfig'
  | 'unrealscript'
  | 'uscript'
  | 'uc'
  | 'uorazor'
  | 'vala'
  | 'verilog'
  | 'vhdl'
  | 'vim'
  | 'warpscript'
  | 'wasm'
  | 'web-idl'
  | 'webidl'
  | 'wgsl'
  | 'wiki'
  | 'wolfram'
  | 'mathematica'
  | 'nb'
  | 'wl'
  | 'wren'
  | 'xeora'
  | 'xeoracube'
  | 'xojo'
  | 'xquery'
  | 'yang'
  | string; // Allow any string for unlisted or custom languages

import { GRAMMARS_DATA } from './grammars';

// Load grammars immediately when module loads
if (NativeLibprisma) {
  NativeLibprisma.loadGrammars(GRAMMARS_DATA);
}

/**
 * Tokenize source code into syntax-highlighted tokens.
 *
 * @param code - The source code to tokenize
 * @param language - The language identifier (e.g., "javascript", "python", "cpp")
 * @returns An array of tokens representing the highlighted code
 *
 * @example
 * ```ts
 * import { tokenize } from 'react-native-libprisma';
 *
 * const tokens = tokenize('const x = 42;', 'javascript');
 * console.log(tokens);
 * // [
 * //   { type: 'keyword', content: 'const' },
 * //   { type: 'text', content: ' x ' },
 * //   ...
 * // ]
 * ```
 */
export function tokenize(code: string, language: Language): Token[] {
  if (!NativeLibprisma) {
    throw new Error(
      'Libprisma Turbo Module is not available. Make sure the native module is properly linked.'
    );
  }

  const jsonString = NativeLibprisma.tokenizeToJson(code, language);
  return JSON.parse(jsonString) as Token[];
}

export * from './themes';
export type { ThemeName, PrismTheme } from './themes';
export * from './utils';
export * from './components';
